---
name: Perl6-Caller
version: 0.01
author:
  - 'Curtis "Ovid" Poe <ovid@cpan.org>'
abstract: OO C<caller()> interface
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Test::More: 0
provides:
  Perl6::Caller:
    file: lib/Perl6/Caller.pm
    version: 0.01
  caller:
    file: lib/Perl6/Caller.pm
    version: 0.01
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
