---
name: Perl6-Caller
version: 0.100
author:
  - 'Curtis "Ovid" Poe <ovid@cpan.org>'
abstract: OO C<caller()> interface
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.35
provides:
  Perl6::Caller:
    file: lib/Perl6/Caller.pm
    version: 0.100
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
